FROM ubuntu:18.04

COPY solution_app/requirements.txt /

# install your dependencies
RUN apt-get update && apt-get install -y build-essential

RUN apt-get update && apt-get install -y \
    python3-pip

RUN python3 -V
RUN pip3 install --no-cache-dir -r /requirements.txt

COPY solution_app/ /app
WORKDIR /app

CMD ["python3", "solution.py"]
